name: simple_store
version: 0.1.0
homepage: https://github.com/inhere/flutter_simple_store
description: A simple local storage for Flutter. Support all platforms.

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.5
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - flutter
  - storage
  - files